#!/usr/bin/env ruby

=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end

N=4000000

fib = Enumerator.new do |y|
  a = b = 1
  loop do
    y.yield a
    a,b = b, a+b
  end
end

sum = 0
n = fib.next
until n > N
  if n % 2 == 0 then sum += n end
  n = fib.next
end

puts sum
