#!/usr/bin/env python
"""Solution to Problem 29 of Project Euler.

See http://projecteuler.net/index.php?section=problems&id=29 for the details.
"""

__author__ = "Charles Patterson"
__copyright__ = "Copyright 2010"
__credits__ = []

__license__ = "GPL"
__version__ = "1.0.0"
__maintainer__ = "Charles Patterson"
__email__ = "charles@cmpatterson.com"
__status__ = "Production"

def project_euler_29():
    """Prints the number of distinct terms generated by a^b for 
    2 <= a,b <= 1000.

    This solution takes advantage of Python's Set data structure."""
    print(len(set([a**b for a in range(2,101) for b in range(2,101)])))

if __name__ == "__main__":
    project_euler_29()

    raw_input("Press Enter to Continue...")
